### ISSUE TITLE
build for Mac fails

### ISSUE THREAD

**Issue by urbien** [my0419/myvpn-desktop#21]
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/my0419/electron-oauth-helper.git
npm ERR! 
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

**Comment by my0419** [comment]
problem is solved, thx.

https://github.com/my0419/myvpn-desktop/commit/456bb916db429d7431ddaa4da2fe8f0130f89d10
