### ISSUE TITLE
https://tool.myvpn.run - Got error when switching to Other Server tab

### ISSUE THREAD

**Issue by cyxou** [my0419/myvpn-desktop#46]
On the web app at https://tool.myvpn.run when switching to __Other Server__ tab, there is an error in the browser console: `TypeError: r(...).isIP is not a function` which results in inability to click on the __Connect to the server and configure the protocol__ button:

![image](https://user-images.githubusercontent.com/5896622/204278040-aad74356-c295-477e-b71b-58e23297be0e.png)

**Comment by my0419** [comment]
Thanks, we'll fix it

**Comment by my0419** [comment]
"Other Version" cannot work on the web because nodejs is required. Disabled for web.
