### ISSUE TITLE
Consider adding a WireGuard option

### ISSUE THREAD

**Issue by tracker1** [my0419/myvpn-desktop#6]
https://www.wireguard.com/

**Comment by my0419** [comment]
We have implemented wireguard support, which will be available in the next release as soon as we fix the problem.

[branch wireguard ](https://github.com/my0419/myvpn-desktop/tree/feature/wireguard)
Bash installation scenario: https://gist.github.com/my0419/e5adf8d1d1102d214bd5c0af8fad3529

**Problem:**
We can see the connected client, but the client has no network.

If anybody's set up before, what might be the problem?

**Comment by my0419** [comment]
we've included wireguard in the 0.0.11 release #7
